# Generated by Django 3.2.4 on 2021-07-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210704_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Field trips materials', 'Field trips materials'), ('Embedded components', 'Embedded components'), ('Tool Boxes and tools', 'Tool Boxes and tools')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
